version: '2'
services:
  counterservice:
    build: counterservice
    mem_limit: 512M
    ports:
      - "8080:8080"
  configservice:
      build: configservice
      mem_limit: 512M
      ports:
        - "8888:8080"